### ISSUE TITLE
Can't select text or URL from the helpful tips in the UI

### ISSUE THREAD

**Issue by allanonmage** [Universal-Debloater-Alliance/universal-android-debloater#132] opened 2023-12-27 23:07 UTC
**Describe the bug**
I noticed webview in the list, so I clicked on it to see what you guys had to say about it.  There's a handy URL there, but I can't click on, nor select, any of the text in the bottom part of the window.

Looking at uad_lists.json, I can see that the helpful text comes from the description field of the item in the list.  In this case, it reads:

```
  {
    "id": "com.android.webview",
    "list": "Aosp",
    "description": "AOSP webview\nDeprecated and replaced by com.google.android.webview\nAllows Android apps to display content from the web directly inside the app. It's based on Chrome.\nWARNING: Make to have another Webview before uninstalling it or some apps may not work properly.\nBromite is an open-source, privacy-oriented Webview replacement: https://www.bromite.org/system_web_view",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
```

While this tool is geared towards more technical users, you shouldn't have to take apart a tool to use it.  For an example, think of simple hand tools, or something a little more sophisticated like a tricorder.

**Expected behavior**
It's text, so I'd expect to be able to slect it, or at least click on links.

**You have a solution?**
Change the UI to make it user friendly, selectable, and/or clickable.

**UAD log**
n/a

**Comment by Frigyes06** [comment] 2023-12-27 23:13
Duplicate of #49

**Closed by Frigyes06** 2023-12-27 23:13 UTC
Labels: bug
