### ISSUE TITLE
DELETE_FAILED_DEVICE_POLICY_MANAGER

### ISSUE THREAD

**Issue by Drjacky** [Universal-Debloater-Alliance/universal-android-debloater#41] opened 2023-11-10 15:55 UTC
`ERROR [src/core/utils.rs:228] [Unlisted] pm uninstall --user 0 com.example -> Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]`

**Comment by Frigyes06** [comment] 2023-11-11 01:29
What package are you trying to uninstall?

**Comment by Drjacky** [comment] 2023-11-11 11:06
> What package are you trying to uninstall?

A system app (which might have a protected package/folder)

**Comment by Frigyes06** [comment] 2023-11-22 00:07
This is not a bug in the program. Best we can do is add that it cannot be uninstalled into the package's description

**Comment by Frigyes06** [comment] 2023-11-23 20:56
Can you tell us which app you were trying to uninstall, so we can add info to it's description?

**Comment by Drjacky** [comment] 2023-11-24 17:28
> Can you tell us which app you were trying to uninstall, so we can add info to it's description?

It's a custom app from a custom AOSP.

**Comment by Frigyes06** [comment] 2023-11-24 18:06
Is it on the list?
I need to know what you want us to fix to close this issue

**Comment by Drjacky** [comment] 2023-11-25 11:31
https://stackoverflow.com/a/54021398/421467 -> https://stackoverflow.com/a/5387620/421467

So, it's an admin app (I think you can simulate this issue by installing [Avast](https://play.google.com/store/apps/details?id=com.avast.android.mobilesecurity)) but the issue with my admin app is the "disabling the admin checkbox" is disabled; I cannot disable that admin app.

**Comment by AnonymousWP** [comment] 2023-11-27 11:27
Try disabling instead of uninstalling. As you may know, you can't uninstall system packages; you can only disable them. Try that instead.

**Comment by Drjacky** [comment] 2023-11-27 13:14
> Try disabling instead of uninstalling. As you may know, you can't uninstall system packages; you can only disable them via ADB. Try that instead.

"Disable Switchbox" is disabled.

**Comment by AnonymousWP** [comment] 2023-11-27 13:34
> > Try disabling instead of uninstalling. As you may know, you can't uninstall system packages; you can only disable them via ADB. Try that instead.
> 
> "Disable Switchbox" is disabled.

Huh? What do you mean with "switchbox"? You're supposed to tick the box "disable instead of uninstall" (or something like that) in the settings.

**Comment by Drjacky** [comment] 2023-11-30 13:03
> > > Try disabling instead of uninstalling. As you may know, you can't uninstall system packages; you can only disable them via ADB. Try that instead.
> > 
> > 
> > "Disable Switchbox" is disabled.
> 
> Huh? What do you mean with "switchbox"? You're supposed to tick the box "disable instead of uninstall" (or something like that) in the settings.

I mean in the OS, the factory of the Android Device has disabled the ability to disable the Admin app.

**Comment by AnonymousWP** [comment] 2023-11-30 19:52
> > > > Try disabling instead of uninstalling. As you may know, you can't uninstall system packages; you can only disable them via ADB. Try that instead.
> > > 
> > > 
> > > "Disable Switchbox" is disabled.
> > 
> > 
> > Huh? What do you mean with "switchbox"? You're supposed to tick the box "disable instead of uninstall" (or something like that) in the settings.
> 
> I mean in the OS, the factory of the Android Device has disabled the ability to disable the Admin app.

Don't use that one on your phone, but disable the app via UAD.

**Comment by Drjacky** [comment] 2023-12-02 11:40
> > > > > Try disabling instead of uninstalling. As you may know, you can't uninstall system packages; you can only disable them via ADB. Try that instead.
> > > > 
> > > > 
> > > > "Disable Switchbox" is disabled.
> > > 
> > > 
> > > Huh? What do you mean with "switchbox"? You're supposed to tick the box "disable instead of uninstall" (or something like that) in the settings.
> > 
> > 
> > I mean in the OS, the factory of the Android Device has disabled the ability to disable the Admin app.
> 
> Don't use that one on your phone, but disable the app via UAD.

This is what brought me to create this issue. It shows this error:
```bash
ERROR [src/core/utils.rs:228] [Unlisted] pm uninstall --user 0 com.example -> Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]
```

**Comment by AnonymousWP** [comment] 2023-12-03 13:57
Is your phone a managed phone by the company you work at? In that case, due to Android policies you can't disable/uninstall certain apps.

**Closed** 2023-12-03 14:20 UTC
Labels: package::documentation, Needs more info
